import {
  UserRole,
  type PrismaClient,
} from "@prisma/client";
import { Router, type RequestHandler } from "express";

import { asyncHandler } from "../../../shared/http/async-handler.js";
import { createRateLimit } from "../../../shared/http/rate-limit.js";
import { requireCurrentRole } from "./admin-authorization.js";
import type { AdminController } from "./admin-controller.js";

export function createAdminRouter(
  controller: AdminController,
  database: PrismaClient,
  authenticate: RequestHandler,
): Router {
  const router = Router();
  const adminOnly = requireCurrentRole(database, [
    UserRole.ADMIN,
    UserRole.SUPER_ADMIN,
  ]);
  const moderationStaff = requireCurrentRole(database, [
    UserRole.MODERATOR,
    UserRole.ADMIN,
    UserRole.SUPER_ADMIN,
  ]);
  const superAdminOnly = requireCurrentRole(database, [UserRole.SUPER_ADMIN]);
  const readLimit = createRateLimit(300, 10 * 60 * 1_000);
  const mutationLimit = createRateLimit(60, 10 * 60 * 1_000);

  router.use(authenticate);
  router.get(
    "/dashboard",
    readLimit,
    adminOnly,
    asyncHandler(controller.dashboard),
  );
  router.get(
    "/users",
    readLimit,
    adminOnly,
    asyncHandler(controller.listUsers),
  );
  router.get(
    "/users/stats",
    readLimit,
    adminOnly,
    asyncHandler(controller.usersStats),
  );
  router.get(
    "/users/:userId",
    readLimit,
    adminOnly,
    asyncHandler(controller.getUser),
  );
  router.get(
    "/users/:userId/moderation-history",
    readLimit,
    adminOnly,
    asyncHandler(controller.listUserModerationHistory),
  );
  router.patch(
    "/users/:userId/status",
    mutationLimit,
    adminOnly,
    asyncHandler(controller.changeUserStatus),
  );
  router.get(
    "/reports",
    readLimit,
    moderationStaff,
    asyncHandler(controller.listReports),
  );
  router.post(
    "/reports/:reportId/resolve",
    mutationLimit,
    moderationStaff,
    asyncHandler(controller.resolveReport),
  );
  router.get(
    "/posts",
    readLimit,
    moderationStaff,
    asyncHandler(controller.listPosts),
  );
  router.get(
    "/posts/stats",
    readLimit,
    moderationStaff,
    asyncHandler(controller.postsStats),
  );
  router.patch(
    "/posts/:postId/visibility",
    mutationLimit,
    moderationStaff,
    asyncHandler(controller.updatePostVisibility),
  );
  router.delete(
    "/posts/:postId",
    mutationLimit,
    moderationStaff,
    asyncHandler(controller.deletePost),
  );
  router.get(
    "/stories",
    readLimit,
    moderationStaff,
    asyncHandler(controller.listStories),
  );
  router.get(
    "/stories/stats",
    readLimit,
    moderationStaff,
    asyncHandler(controller.storiesStats),
  );
  router.delete(
    "/stories/:storyId",
    mutationLimit,
    moderationStaff,
    asyncHandler(controller.deleteStory),
  );
  router.get(
    "/comments",
    readLimit,
    moderationStaff,
    asyncHandler(controller.listComments),
  );
  router.patch(
    "/comments/:commentId/visibility",
    mutationLimit,
    moderationStaff,
    asyncHandler(controller.updateCommentVisibility),
  );
  router.delete(
    "/comments/:commentId",
    mutationLimit,
    moderationStaff,
    asyncHandler(controller.deleteComment),
  );
  router.get(
    "/audit-logs",
    readLimit,
    adminOnly,
    asyncHandler(controller.listAuditLogs),
  );
  router.get(
    "/staff",
    readLimit,
    adminOnly,
    asyncHandler(controller.listStaff),
  );
  router.patch(
    "/staff/:userId/role",
    mutationLimit,
    superAdminOnly,
    asyncHandler(controller.changeStaffRole),
  );
  router.patch(
    "/users/:userId/verified-badge",
    mutationLimit,
    adminOnly,
    asyncHandler(controller.setVerifiedBadge),
  );
  router.get(
    "/interest-tags",
    readLimit,
    adminOnly,
    asyncHandler(controller.listInterestTags),
  );
  router.post(
    "/interest-tags",
    mutationLimit,
    adminOnly,
    asyncHandler(controller.createInterestTag),
  );
  router.patch(
    "/interest-tags/:tagId",
    mutationLimit,
    adminOnly,
    asyncHandler(controller.updateInterestTag),
  );
  router.get(
    "/analytics",
    readLimit,
    adminOnly,
    asyncHandler(controller.getAnalytics),
  );
  router.get(
    "/premium-plans",
    readLimit,
    adminOnly,
    asyncHandler(controller.listPremiumPlans),
  );
  router.post(
    "/premium-plans",
    mutationLimit,
    adminOnly,
    asyncHandler(controller.createPremiumPlan),
  );
  router.patch(
    "/premium-plans/:planId",
    mutationLimit,
    adminOnly,
    asyncHandler(controller.updatePremiumPlan),
  );
  router.get(
    "/subscriptions",
    readLimit,
    adminOnly,
    asyncHandler(controller.listSubscriptions),
  );
  router.post(
    "/subscriptions",
    mutationLimit,
    adminOnly,
    asyncHandler(controller.grantSubscription),
  );
  router.post(
    "/subscriptions/:subscriptionId/cancel",
    mutationLimit,
    adminOnly,
    asyncHandler(controller.cancelSubscription),
  );
  router.get(
    "/ads",
    readLimit,
    adminOnly,
    asyncHandler(controller.listAds),
  );
  router.post(
    "/ads",
    mutationLimit,
    adminOnly,
    asyncHandler(controller.createAd),
  );
  router.patch(
    "/ads/:adId",
    mutationLimit,
    adminOnly,
    asyncHandler(controller.updateAd),
  );
  router.delete(
    "/ads/:adId",
    mutationLimit,
    adminOnly,
    asyncHandler(controller.deleteAd),
  );
  router.get(
    "/cms-pages",
    readLimit,
    adminOnly,
    asyncHandler(controller.listCmsPages),
  );
  router.post(
    "/cms-pages",
    mutationLimit,
    adminOnly,
    asyncHandler(controller.createCmsPage),
  );
  router.patch(
    "/cms-pages/:pageId",
    mutationLimit,
    adminOnly,
    asyncHandler(controller.updateCmsPage),
  );
  router.get(
    "/matches/stats",
    readLimit,
    adminOnly,
    asyncHandler(controller.matchesStats),
  );
  router.get(
    "/matches",
    readLimit,
    adminOnly,
    asyncHandler(controller.listMatches),
  );
  router.get(
    "/conversations/stats",
    readLimit,
    moderationStaff,
    asyncHandler(controller.conversationsStats),
  );
  router.get(
    "/conversations/:conversationId/messages",
    readLimit,
    moderationStaff,
    asyncHandler(controller.listConversationMessages),
  );
  router.get(
    "/conversations",
    readLimit,
    moderationStaff,
    asyncHandler(controller.listConversations),
  );
  router.delete(
    "/messages/:messageId",
    mutationLimit,
    moderationStaff,
    asyncHandler(controller.deleteMessage),
  );
  router.get(
    "/media",
    readLimit,
    adminOnly,
    asyncHandler(controller.listMedia),
  );
  router.get(
    "/media/:mediaId/content",
    readLimit,
    adminOnly,
    asyncHandler(controller.getMediaContent),
  );
  router.patch(
    "/media/:mediaId",
    mutationLimit,
    adminOnly,
    asyncHandler(controller.updateMedia),
  );
  router.get(
    "/outbox-events",
    readLimit,
    adminOnly,
    asyncHandler(controller.listOutboxEvents),
  );
  router.post(
    "/outbox-events/:eventId/retry",
    mutationLimit,
    adminOnly,
    asyncHandler(controller.retryOutboxEvent),
  );
  router.get(
    "/email-jobs",
    readLimit,
    adminOnly,
    asyncHandler(controller.listEmailJobs),
  );
  router.post(
    "/email-jobs/:jobId/retry",
    mutationLimit,
    adminOnly,
    asyncHandler(controller.retryEmailJob),
  );
  router.get(
    "/hashtags",
    readLimit,
    adminOnly,
    asyncHandler(controller.listHashtags),
  );
  router.delete(
    "/hashtags/:hashtagId",
    mutationLimit,
    adminOnly,
    asyncHandler(controller.deleteHashtag),
  );
  return router;
}
